name: Deploy to GitHub Pages   # 워크플로 이름, 아무거나 OK

# 고아(Queued) 런 자동 취소
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: ["main"]         # 배포용 브랜치

# GitHub Pages에 필요한 권한
permissions:
  contents: read
  p
