name: Deploy to GitHub Pages

# ★ 고아 런 방지
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: ["main"]   # ← 기본 브랜치 이름 그대로

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 한 장 이미지 그대로 배포할 거라 별도 빌드 없이
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .        # 리포 루트 전체를 그대로 아티팩트로
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
