name: Deploy to GitHub Pages

# ★ 고아 런 방지
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: ["main"]   # ← 기본 브랜치 이름 그대로

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted        # ← 로컬 러너가 바로 받도록
   steps:
       - uses: actions/checkout@v4
       - uses: actions/upload-pages-artifact@v3
         with:
           path: .

  deploy:
    runs-on: self-hosted        # ← 역시 self-hosted

     needs: build
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     steps:
       - id: deployment
         uses: actions/deploy-pages@v4
