name: Deploy to GitHub Pages   


concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: ["main"]         


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted       
    steps:
      - uses: actions/checkout@v4

  
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .              

  deploy:
    runs-on: self-hosted       
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
